language: node_js

node_js:
  - "8"

cache:
  directories:
    - .npm

before_install:
  - npm install codecov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  directories:
    - .npm
